### ISSUE TITLE
Thinking this might be a platform issue... 

### ISSUE THREAD

**Issue by bentman** [bentman/PoSH-BatteryReportCollection#4]
Transcript started, output file is C:\temp\BatteryReport\BatteryReportCollection.log

Script Version = 1.5
Invoke-BatteryReportCollection.ps1

VERBOSE: Perform operation 'Query CimInstances' with following parameters, ''queryExpression' = SELECT * FROM __Namespace WHERE Name='BatteryReport','queryDialect' = WQL,'namespaceName' = root\cimv2'.
VERBOSE: Operation 'Query CimInstances' complete.
VERBOSE: Perform operation 'Get CimClass' with following parameters, ''namespaceName' = root\cimv2\BatteryReport,'className' = BatteryReport'.
VERBOSE: Operation 'Get CimClass' complete.
Creating class: BatteryReport
New-CimClass : Failed to create the class BatteryReport in the namespace root\cimv2\BatteryReport. Error: Attempt to 
modify read-only object or property failed 
At D:\USR\Invoke-BatteryReportCollection.ps1:144 char:9
+         New-CimClass -namespacePath $namespacePath -newClassName $new ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-CimClass
New-CimClass : Failed to create the class BatteryReport in the namespace root\cimv2\BatteryReport. Error: Attempt to modify
read-only object or property failed
At D:\USR\Invoke-BatteryReportCollection.ps1:144 char:9
+         New-CimClass -namespacePath $namespacePath -newClassName $new ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-CimClass

Battery life report saved to file path C:\temp\BatteryReport\batteryreport.html.
Battery life report saved to file path C:\temp\BatteryReport\batteryreport.xml.
Get-CimInstance : Invalid class 
At D:\USR\Invoke-BatteryReportCollection.ps1:184 char:17
+ ... $instance = Get-CimInstance -Namespace $namespacePath -ClassName $new ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (root\cimv2\BatteryReport:BatteryReport:String) [Get-CimInstance], 
CimException
    + FullyQualifiedErrorId : HRESULT 0x80041010,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand
Get-CimInstance : Invalid class
At D:\USR\Invoke-BatteryReportCollection.ps1:184 char:17
+ ... $instance = Get-CimInstance -Namespace $namespacePath -ClassName $new ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (root\cimv2\BatteryReport:BatteryReport:String) [Get-CimInstance], CimException
    + FullyQualifiedErrorId : HRESULT 0x80041010,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand

PS>TerminatingError(Set-WmiInstance): "A positional parameter cannot be found that accepts argument '+'."
Error: A positional parameter cannot be found that accepts argument '+'.
Get-CimInstance : Invalid class 
At D:\USR\Invoke-BatteryReportCollection.ps1:200 char:21
+ ... Instances = Get-CimInstance -Namespace $namespacePath -ClassName $new ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (root\cimv2\BatteryReport:BatteryReport:String) [Get-CimInstance], 
CimException
    + FullyQualifiedErrorId : HRESULT 0x80041010,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand
Get-CimInstance : Invalid class
At D:\USR\Invoke-BatteryReportCollection.ps1:200 char:21
+ ... Instances = Get-CimInstance -Namespace $namespacePath -ClassName $new ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (root\cimv2\BatteryReport:BatteryReport:String) [Get-CimInstance], CimException
    + FullyQualifiedErrorId : HRESULT 0x80041010,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand

New Class: BatteryReport
**********************
Windows PowerShell transcript end
End time: 20230728095745
**********************

**Comment by bentman** [comment]
Mayb a platform issues (running on a Surface Go-3). Added debug strings for the catch section.

**Comment by bentman** [comment]
New-CimClass : Failed to create the class BatteryReport in the namespace root\cimv2\BatteryReport. Error: Attempt to modify
read-only object or property failed
At D:\USR\Invoke-BatteryReportCollection.ps1:150 char:9
+         New-CimClass -namespacePath $namespacePath -newClassName $new ...
+         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorException
    + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorException,New-CimClass

Battery life report saved to file path C:\temp\BatteryReport\batteryreport.html.
Battery life report saved to file path C:\temp\BatteryReport\batteryreport.xml.
Get-CimInstance : Invalid class
At D:\USR\Invoke-BatteryReportCollection.ps1:190 char:17
+ ... $instance = Get-CimInstance -Namespace $namespacePath -ClassName $new ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (root\cimv2\BatteryReport:BatteryReport:String) [Get-CimInstance], CimException
    + FullyQualifiedErrorId : HRESULT 0x80041010,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand

Error: A positional parameter cannot be found that accepts argument '+'.
Stack Trace:    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Command Origin: System.Management.Automation.InvocationInfo
Get-CimInstance : Invalid class
At D:\USR\Invoke-BatteryReportCollection.ps1:208 char:21
+ ... Instances = Get-CimInstance -Namespace $namespacePath -ClassName $new ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (root\cimv2\BatteryReport:BatteryReport:String) [Get-CimInstance], CimException
    + FullyQualifiedErrorId : HRESULT 0x80041010,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand


New Class: BatteryReport
Transcript stopped, output file is C:\temp\BatteryReport\BatteryReportCollection.log
