### ISSUE TITLE
v2.0 - Errors

### ISSUE THREAD

**Issue by bentman** [bentman/PoSH-BatteryReportCollection#5]
Get-CimInstance : Invalid class
At D:\USR\Invoke-BatteryReportCollection.ps1:190 char:17
+ ... $instance = Get-CimInstance -Namespace $namespacePath -ClassName $new ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (root\cimv2\BatteryReport:BatteryReport:String) [Get-CimInstance], CimException
    + FullyQualifiedErrorId : HRESULT 0x80041010,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand

Error: A positional parameter cannot be found that accepts argument '+'.
Stack Trace:    at System.Management.Automation.ExceptionHandlingOps.CheckActionPreference(FunctionContext funcContext, Exception exception)
   at System.Management.Automation.Interpreter.ActionCallInstruction`2.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
   at System.Management.Automation.Interpreter.EnterTryCatchFinallyInstruction.Run(InterpretedFrame frame)
Command Origin: System.Management.Automation.InvocationInfo
Get-CimInstance : Invalid class
At D:\USR\Invoke-BatteryReportCollection.ps1:208 char:21
+ ... Instances = Get-CimInstance -Namespace $namespacePath -ClassName $new ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : MetadataError: (root\cimv2\BatteryReport:BatteryReport:String) [Get-CimInstance], CimException
    + FullyQualifiedErrorId : HRESULT 0x80041010,Microsoft.Management.Infrastructure.CimCmdlets.GetCimInstanceCommand

**Comment by bentman** [comment]
Error: Cannot bind parameter 'Property'. Cannot convert the "System.Management.Automation.PSMemberInfoIntegratingCollection`1[System.Management.Automation.PSPropertyInfo]" value of type "System.Management.Automation.PSMemberInfoIntegratingCollection`1[[System.Management.Automation.PSPropertyInfo, System.Management.Automation, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]" to type "System.Collections.IDictionary".

**Comment by bentman** [comment]
Error: Could not infer CimType from the provided .NET object.

**Comment by bentman** [comment]
<?xml version="1.0" encoding="utf-8"?>
<?xml-stylesheet type='text/xsl' href='C:\battery-stylesheet.xsl'?>
<BatteryReport xmlns="http://schemas.microsoft.com/battery/2012">
  <ReportInformation>
    <ReportGuid>2963087f-e1e6-46b5-927d-17380669ebd1</ReportGuid>
    <ReportVersion>1.1</ReportVersion>
    <ScanTime>2023-07-28T21:09:53Z</ScanTime>
    <LocalScanTime>2023-07-28T16:09:53</LocalScanTime>
    <ReportStartTime>2023-07-25T21:09:53Z</ReportStartTime>
    <LocalReportStartTime>2023-07-25T16:09:53</LocalReportStartTime>
    <ReportDuration>3</ReportDuration>
    <UtcOffset>-5:00</UtcOffset>
  </ReportInformation>
  <SystemInformation>
    <ComputerName>S0B33W6M</ComputerName>
    <SystemManufacturer>Microsoft Corporation</SystemManufacturer>
    <SystemProductName>Surface Go 3</SystemProductName>
    <BIOSDate>02/09/2022</BIOSDate>
    <BIOSVersion>9.103.143</BIOSVersion>
    <OSBuild>22621.1.amd64fre.ni_release.220506-1250</OSBuild>
    <PlatformRole>Slate</PlatformRole>
    <ConnectedStandby>1</ConnectedStandby>
  </SystemInformation>
  <Batteries>
    <Battery>
      <Id>SurfaceBattery</Id>
      <Manufacturer>SMP</Manufacturer>
      <SerialNumber>0</SerialNumber>
      <ManufactureDate></ManufactureDate>
      <Chemistry>LION</Chemistry>
      <LongTerm>1</LongTerm>
      <RelativeCapacity>0</RelativeCapacity>
      <DesignCapacity>26810</DesignCapacity>
      <FullChargeCapacity>24834</FullChargeCapacity>
      <CycleCount>14</CycleCount>
    </Battery>
  </Batteries>
  <RuntimeEstimates>
    <DesignCapacity>
      <Capacity>26810</Capacity>
      <ActiveRuntime>PT0S</ActiveRuntime>
      <ConnectedStandbyRuntime>P6DT17H8M12S</ConnectedStandbyRuntime>
    </DesignCapacity>
    <FullChargeCapacity>
      <Capacity>24834</Capacity>
      <ActiveRuntime>PT0S</ActiveRuntime>
      <ConnectedStandbyRuntime>P6DT5H15M37S</ConnectedStandbyRuntime>
    </FullChargeCapacity>
  </RuntimeEstimates>
  <RecentUsage>
    <UsageEntry
      Timestamp="2023-07-28T10:53:53Z"
      LocalTimestamp="2023-07-28T05:53:53"
      Duration="15708148"
      Ac="1"
      EntryType="ConnectedStandby"
      ChargeCapacity="4182"
      Discharge="-8"
      FullChargeCapacity="24780"
      IsNextOnBattery="0"
      />
    <UsageEntry
      Timestamp="2023-07-28T10:53:54Z"
      LocalTimestamp="2023-07-28T05:53:54"
      Duration="19537184898"
      Ac="1"
      EntryType="Active"
      ChargeCapacity="4190"
      Discharge="-3616"
      FullChargeCapacity="24780"
      IsNextOnBattery="0"
      />
    <UsageEntry
      Timestamp="2023-07-28T11:26:28Z"
      LocalTimestamp="2023-07-28T06:26:28"
      Duration="2337561852"
      Ac="1"
      EntryType="Suspend"
      ChargeCapacity="7806"
      Discharge="-643"
      FullChargeCapacity="24780"
      IsNextOnBattery="0"
      />
    <UsageEntry
      Timestamp="2023-07-28T11:30:22Z"
      LocalTimestamp="2023-07-28T06:30:22"
      Duration="0"
      Ac="1"
      EntryType="Active"
      ChargeCapacity="8449"
      Discharge="0"
      FullChargeCapacity="24780"
      IsNextOnBattery="0"
      />
    <UsageEntry
      Timestamp="2023-07-28T11:30:22Z"
      LocalTimestamp="2023-07-28T06:30:22"
      Duration="1188421943"
      Ac="1"
      EntryType="Suspend"
      ChargeCapacity="8449"
      Discharge="-253"
      FullChargeCapacity="24780"
      IsNextOnBattery="0"
      />
    <UsageEntry
      Timestamp="2023-07-28T11:32:20Z"
      LocalTimestamp="2023-07-28T06:32:20"
      Duration="11684228834"
      Ac="1"
      EntryType="Active"
      ChargeCapacity="8702"
      Discharge="-3317"
      FullChargeCapacity="24780"
      IsNextOnBattery="0"
      />
    <UsageEntry
      Timestamp="2023-07-28T11:51:49Z"
      LocalTimestamp="2023-07-28T06:51:49"
      Duration="707982685"
      Ac="1"
      EntryType="ConnectedStandby"
      ChargeCapacity="12019"
      Discharge="-107"
      FullChargeCapacity="24780"
      IsNextOnBattery="0"
      />
    <UsageEntry
      Timestamp="2023-07-28T11:53:00Z"
      LocalTimestamp="2023-07-28T06:53:00"
      Duration="9036705084"
      Ac="1"
      EntryType="Active"
      ChargeCapacity="12126"
      Discharge="-2872"
      FullChargeCapacity="24780"
      IsNextOnBattery="0"
      />
    <UsageEntry
      Timestamp="2023-07-28T12:08:03Z"
      LocalTimestamp="2023-07-28T07:08:03"
      Duration="1920602366"
      Ac="1"
      EntryType="ConnectedStandby"
      ChargeCapacity="14998"
      Discharge="-1004"
      FullChargeCapacity="24780"
      IsNextOnBattery="0"
      />
    <UsageEntry
      Timestamp="2023-07-28T12:11:15Z"
      LocalTimestamp="2023-07-28T07:11:15"
      Duration="7396597033"
      Ac="1"
      EntryType="Active"
      ChargeCapacity="16002"
      Discharge="-3309"
      FullChargeCapacity="24780"
      IsNextOnBattery="0"
      />
    <UsageEntry
      Timestamp="2023-07-28T12:23:35Z"
      LocalTimestamp="2023-07-28T07:23:35"
      Duration="2768916072"
      Ac="1"
      EntryType="ConnectedStandby"
      ChargeCapacity="19311"
      Discharge="-904"
      FullChargeCapacity="24780"
      IsNextOnBattery="0"
      />
    <UsageEntry
      Timestamp="2023-07-28T12:28:12Z"
      LocalTimestamp="2023-07-28T07:28:12"
      Duration="28675802567"
      Ac="1"
      EntryType="Active"
      ChargeCapacity="20215"
      Discharge="-4259"
      FullChargeCapacity="24780"
      IsNextOnBattery="0"
      />
    <UsageEntry
      Timestamp="2023-07-28T13:16:00Z"
      LocalTimestamp="2023-07-28T08:16:00"
      Duration="653698913"
      Ac="1"
      EntryType="Suspend"
      ChargeCapacity="24474"
      Discharge="-38"
      FullChargeCapacity="24780"
      IsNextOnBattery="0"
      />
    <UsageEntry
      Timestamp="2023-07-28T13:17:05Z"
      LocalTimestamp="2023-07-28T08:17:05"
      Duration="12697474849"
      Ac="1"
      EntryType="Active"
      ChargeCapacity="24512"
      Discharge="-444"
      FullChargeCapacity="24780"
      IsNextOnBattery="0"
      />
    <UsageEntry
      Timestamp="2023-07-28T13:38:15Z"
      LocalTimestamp="2023-07-28T08:38:15"
      Duration="33034803110"
      Ac="1"
      EntryType="ConnectedStandby"
      ChargeCapacity="24956"
      Discharge="0"
      FullChargeCapacity="24956"
      IsNextOnBattery="0"
      />
    <UsageEntry
      Timestamp="2023-07-28T14:33:18Z"
      LocalTimestamp="2023-07-28T09:33:18"
      Duration="24761904925"
      Ac="1"
      EntryType="Active"
      ChargeCapacity="24956"
      Discharge="0"
      FullChargeCapacity="24956"
      IsNextOnBattery="0"
      />
    <UsageEntry
      Timestamp="2023-07-28T15:14:34Z"
      LocalTimestamp="2023-07-28T10:14:34"
      Duration="5407208498"
      Ac="1"
      EntryType="ConnectedStandby"
      ChargeCapacity="24956"
      Discharge="0"
      FullChargeCapacity="24956"
      IsNextOnBattery="0"
      />
    <UsageEntry
      Timestamp="2023-07-28T15:23:35Z"
      LocalTimestamp="2023-07-28T10:23:35"
      Duration="10823518872"
      Ac="1"
      EntryType="Active"
      ChargeCapacity="24956"
      Discharge="0"
      FullChargeCapacity="24956"
      IsNextOnBattery="0"
      />
    <UsageEntry
      Timestamp="2023-07-28T15:41:37Z"
      LocalTimestamp="2023-07-28T10:41:37"
      Duration="24902791651"
      Ac="1"
      EntryType="ConnectedStandby"
      ChargeCapacity="24956"
      Discharge="0"
      FullChargeCapacity="24956"
      IsNextOnBattery="0"
      />
    <UsageEntry
      Timestamp="2023-07-28T16:23:08Z"
      LocalTimestamp="2023-07-28T11:23:08"
      Duration="10271442979"
      Ac="1"
      EntryType="Active"
      ChargeCapacity="24956"
      Discharge="0"
      FullChargeCapacity="24956"
      IsNextOnBattery="0"
      />
    <UsageEntry
      Timestamp="2023-07-28T16:40:15Z"
      LocalTimestamp="2023-07-28T11:40:15"
      Duration="34279841659"
      Ac="1"
      EntryType="ConnectedStandby"
      ChargeCapacity="24956"
      Discharge="0"
      FullChargeCapacity="24956"
      IsNextOnBattery="0"
      />
    <UsageEntry
      Timestamp="2023-07-28T17:37:23Z"
      LocalTimestamp="2023-07-28T12:37:23"
      Duration="11687020674"
      Ac="1"
      EntryType="Active"
      ChargeCapacity="24956"
      Discharge="0"
      FullChargeCapacity="24956"
      IsNextOnBattery="0"
      />
    <UsageEntry
      Timestamp="2023-07-28T17:56:51Z"
      LocalTimestamp="2023-07-28T12:56:51"
      Duration="27779925003"
      Ac="1"
      EntryType="ConnectedStandby"
      ChargeCapacity="24956"
      Discharge="122"
      FullChargeCapacity="24956"
      IsNextOnBattery="0"
      />
    <UsageEntry
      Timestamp="2023-07-28T18:43:09Z"
      LocalTimestamp="2023-07-28T13:43:09"
      Duration="18666253608"
      Ac="1"
      EntryType="Active"
      ChargeCapacity="24834"
      Discharge="0"
      FullChargeCapacity="24834"
      IsNextOnBattery="0"
      />
    <UsageEntry
      Timestamp="2023-07-28T19:14:16Z"
      LocalTimestamp="2023-07-28T14:14:16"
      Duration="36583978094"
      Ac="1"
      EntryType="ConnectedStandby"
      ChargeCapacity="24834"
      Discharge="0"
      FullChargeCapacity="24834"
      IsNextOnBattery="0"
      />
    <UsageEntry
      Timestamp="2023-07-28T20:15:15Z"
      LocalTimestamp="2023-07-28T15:15:15"
      Duration="13128987077"
      Ac="1"
      EntryType="Active"
      ChargeCapacity="24834"
      Discharge="0"
      FullChargeCapacity="24834"
      IsNextOnBattery="0"
      />
    <UsageEntry
      Timestamp="2023-07-28T20:37:07Z"
      LocalTimestamp="2023-07-28T15:37:07"
      Duration="3571301657"
      Ac="1"
      EntryType="ConnectedStandby"
      ChargeCapacity="24834"
      Discharge="0"
      FullChargeCapacity="24834"
      IsNextOnBattery="0"
      />
    <UsageEntry
      Timestamp="2023-07-28T20:43:05Z"
      LocalTimestamp="2023-07-28T15:43:05"
      Duration="16084556760"
      Ac="1"
      EntryType="Active"
      ChargeCapacity="24834"
      Discharge="0"
      FullChargeCapacity="24834"
      IsNextOnBattery="0"
      />
    <UsageEntry
      Timestamp="2023-07-28T21:09:53Z"
      LocalTimestamp="2023-07-28T16:09:53"
      Duration="18446744073708297550"
      Ac="1"
      EntryType="ReportGenerated"
      ChargeCapacity="24834"
      Discharge="0"
      FullChargeCapacity="24834"
      IsNextOnBattery="0"
      />
  </RecentUsage>
  <History>
    <HistoryEntry
      StartDate="2023-05-30T15:02:45Z"
      LocalStartDate="2023-05-30T10:02:45"
      EndDate="2023-06-06T15:02:45Z"
      LocalEndDate="2023-06-06T10:02:45"
      DesignCapacity="26810"
      FullChargeCapacity="24976"
      CycleCount="13"
      ActiveAcTime="PT21H22M37S"
      ActiveDcTime="PT0S"
      CsAcTime="PT42M23S"
      CsDcTime="P6DT1H45M45S"
      ActiveDcEnergy="0"
      CsDcEnergy="24252"
      EstimatedDesignActiveTime="PT0S"
      EstimatedFullChargeActiveTime="PT0S"
      EstimatedDesignCsTime="P6DT17H8M12S"
      EstimatedFullChargeCsTime="P6DT6H6M50S"
      BatteryChanged="0"
      />
    <HistoryEntry
      StartDate="2023-06-06T15:02:45Z"
      LocalStartDate="2023-06-06T10:02:45"
      EndDate="2023-06-13T15:02:45Z"
      LocalEndDate="2023-06-13T10:02:45"
      DesignCapacity="26810"
      FullChargeCapacity="24780"
      CycleCount="14"
      ActiveAcTime="P6DT23H59M59S"
      ActiveDcTime="PT0S"
      CsAcTime="PT0S"
      CsDcTime="PT0S"
      ActiveDcEnergy="0"
      CsDcEnergy="0"
      EstimatedDesignActiveTime="PT0S"
      EstimatedFullChargeActiveTime="PT0S"
      EstimatedDesignCsTime="PT0S"
      EstimatedFullChargeCsTime="PT0S"
      BatteryChanged="0"
      />
    <HistoryEntry
      StartDate="2023-06-13T15:02:45Z"
      LocalStartDate="2023-06-13T10:02:45"
      EndDate="2023-06-20T15:02:45Z"
      LocalEndDate="2023-06-20T10:02:45"
      DesignCapacity="26810"
      FullChargeCapacity="24780"
      CycleCount="14"
      ActiveAcTime="P6DT23H59M59S"
      ActiveDcTime="PT0S"
      CsAcTime="PT0S"
      CsDcTime="PT0S"
      ActiveDcEnergy="0"
      CsDcEnergy="0"
      EstimatedDesignActiveTime="PT0S"
      EstimatedFullChargeActiveTime="PT0S"
      EstimatedDesignCsTime="PT0S"
      EstimatedFullChargeCsTime="PT0S"
      BatteryChanged="0"
      />
    <HistoryEntry
      StartDate="2023-06-20T15:02:45Z"
      LocalStartDate="2023-06-20T10:02:45"
      EndDate="2023-06-27T15:02:45Z"
      LocalEndDate="2023-06-27T10:02:45"
      DesignCapacity="26810"
      FullChargeCapacity="24780"
      CycleCount="14"
      ActiveAcTime="P6DT23H59M59S"
      ActiveDcTime="PT0S"
      CsAcTime="PT0S"
      CsDcTime="PT0S"
      ActiveDcEnergy="0"
      CsDcEnergy="0"
      EstimatedDesignActiveTime="PT0S"
      EstimatedFullChargeActiveTime="PT0S"
      EstimatedDesignCsTime="PT0S"
      EstimatedFullChargeCsTime="PT0S"
      BatteryChanged="0"
      />
    <HistoryEntry
      StartDate="2023-06-27T15:02:45Z"
      LocalStartDate="2023-06-27T10:02:45"
      EndDate="2023-07-04T15:02:45Z"
      LocalEndDate="2023-07-04T10:02:45"
      DesignCapacity="26810"
      FullChargeCapacity="24780"
      CycleCount="14"
      ActiveAcTime="P6DT23H59M59S"
      ActiveDcTime="PT0S"
      CsAcTime="PT0S"
      CsDcTime="PT0S"
      ActiveDcEnergy="0"
      CsDcEnergy="0"
      EstimatedDesignActiveTime="PT0S"
      EstimatedFullChargeActiveTime="PT0S"
      EstimatedDesignCsTime="PT0S"
      EstimatedFullChargeCsTime="PT0S"
      BatteryChanged="0"
      />
    <HistoryEntry
      StartDate="2023-07-04T15:02:45Z"
      LocalStartDate="2023-07-04T10:02:45"
      EndDate="2023-07-11T15:02:45Z"
      LocalEndDate="2023-07-11T10:02:45"
      DesignCapacity="26810"
      FullChargeCapacity="24780"
      CycleCount="14"
      ActiveAcTime="P6DT23H59M59S"
      ActiveDcTime="PT0S"
      CsAcTime="PT0S"
      CsDcTime="PT0S"
      ActiveDcEnergy="0"
      CsDcEnergy="0"
      EstimatedDesignActiveTime="PT0S"
      EstimatedFullChargeActiveTime="PT0S"
      EstimatedDesignCsTime="PT0S"
      EstimatedFullChargeCsTime="PT0S"
      BatteryChanged="0"
      />
    <HistoryEntry
      StartDate="2023-07-11T15:02:45Z"
      LocalStartDate="2023-07-11T10:02:45"
      EndDate="2023-07-18T15:02:45Z"
      LocalEndDate="2023-07-18T10:02:45"
      DesignCapacity="26810"
      FullChargeCapacity="24780"
      CycleCount="14"
      ActiveAcTime="P6DT23H59M59S"
      ActiveDcTime="PT0S"
      CsAcTime="PT0S"
      CsDcTime="PT0S"
      ActiveDcEnergy="0"
      CsDcEnergy="0"
      EstimatedDesignActiveTime="PT0S"
      EstimatedFullChargeActiveTime="PT0S"
      EstimatedDesignCsTime="PT0S"
      EstimatedFullChargeCsTime="PT0S"
      BatteryChanged="0"
      />
    <HistoryEntry
      StartDate="2023-07-19T05:00:00Z"
      LocalStartDate="2023-07-19T00:00:00"
      EndDate="2023-07-20T04:59:59Z"
      LocalEndDate="2023-07-19T23:59:59"
      DesignCapacity="26810"
      FullChargeCapacity="24780"
      CycleCount="14"
      ActiveAcTime="PT23H59M59S"
      ActiveDcTime="PT0S"
      CsAcTime="PT0S"
      CsDcTime="PT0S"
      ActiveDcEnergy="0"
      CsDcEnergy="0"
      EstimatedDesignActiveTime="PT0S"
      EstimatedFullChargeActiveTime="PT0S"
      EstimatedDesignCsTime="PT0S"
      EstimatedFullChargeCsTime="PT0S"
      BatteryChanged="0"
      />
    <HistoryEntry
      StartDate="2023-07-20T05:00:00Z"
      LocalStartDate="2023-07-20T00:00:00"
      EndDate="2023-07-21T04:59:59Z"
      LocalEndDate="2023-07-20T23:59:59"
      DesignCapacity="26810"
      FullChargeCapacity="24780"
      CycleCount="14"
      ActiveAcTime="PT23H59M59S"
      ActiveDcTime="PT0S"
      CsAcTime="PT0S"
      CsDcTime="PT0S"
      ActiveDcEnergy="0"
      CsDcEnergy="0"
      EstimatedDesignActiveTime="PT0S"
      EstimatedFullChargeActiveTime="PT0S"
      EstimatedDesignCsTime="PT0S"
      EstimatedFullChargeCsTime="PT0S"
      BatteryChanged="0"
      />
    <HistoryEntry
      StartDate="2023-07-21T05:00:00Z"
      LocalStartDate="2023-07-21T00:00:00"
      EndDate="2023-07-22T04:59:59Z"
      LocalEndDate="2023-07-21T23:59:59"
      DesignCapacity="26810"
      FullChargeCapacity="24780"
      CycleCount="14"
      ActiveAcTime="PT23H59M59S"
      ActiveDcTime="PT0S"
      CsAcTime="PT0S"
      CsDcTime="PT0S"
      ActiveDcEnergy="0"
      CsDcEnergy="0"
      EstimatedDesignActiveTime="PT0S"
      EstimatedFullChargeActiveTime="PT0S"
      EstimatedDesignCsTime="PT0S"
      EstimatedFullChargeCsTime="PT0S"
      BatteryChanged="0"
      />
    <HistoryEntry
      StartDate="2023-07-22T05:00:00Z"
      LocalStartDate="2023-07-22T00:00:00"
      EndDate="2023-07-23T04:59:59Z"
      LocalEndDate="2023-07-22T23:59:59"
      DesignCapacity="26810"
      FullChargeCapacity="24780"
      CycleCount="14"
      ActiveAcTime="PT23H59M59S"
      ActiveDcTime="PT0S"
      CsAcTime="PT0S"
      CsDcTime="PT0S"
      ActiveDcEnergy="0"
      CsDcEnergy="0"
      EstimatedDesignActiveTime="PT0S"
      EstimatedFullChargeActiveTime="PT0S"
      EstimatedDesignCsTime="PT0S"
      EstimatedFullChargeCsTime="PT0S"
      BatteryChanged="0"
      />
    <HistoryEntry
      StartDate="2023-07-23T05:00:00Z"
      LocalStartDate="2023-07-23T00:00:00"
      EndDate="2023-07-24T04:59:59Z"
      LocalEndDate="2023-07-23T23:59:59"
      DesignCapacity="26810"
      FullChargeCapacity="24780"
      CycleCount="14"
      ActiveAcTime="PT23H59M59S"
      ActiveDcTime="PT0S"
      CsAcTime="PT0S"
      CsDcTime="PT0S"
      ActiveDcEnergy="0"
      CsDcEnergy="0"
      EstimatedDesignActiveTime="PT0S"
      EstimatedFullChargeActiveTime="PT0S"
      EstimatedDesignCsTime="PT0S"
      EstimatedFullChargeCsTime="PT0S"
      BatteryChanged="0"
      />
    <HistoryEntry
      StartDate="2023-07-24T05:00:00Z"
      LocalStartDate="2023-07-24T00:00:00"
      EndDate="2023-07-25T04:59:59Z"
      LocalEndDate="2023-07-24T23:59:59"
      DesignCapacity="26810"
      FullChargeCapacity="24780"
      CycleCount="14"
      ActiveAcTime="PT23H59M59S"
      ActiveDcTime="PT0S"
      CsAcTime="PT0S"
      CsDcTime="PT0S"
      ActiveDcEnergy="0"
      CsDcEnergy="0"
      EstimatedDesignActiveTime="PT0S"
      EstimatedFullChargeActiveTime="PT0S"
      EstimatedDesignCsTime="PT0S"
      EstimatedFullChargeCsTime="PT0S"
      BatteryChanged="0"
      />
    <HistoryEntry
      StartDate="2023-07-25T05:00:00Z"
      LocalStartDate="2023-07-25T00:00:00"
      EndDate="2023-07-26T04:59:59Z"
      LocalEndDate="2023-07-25T23:59:59"
      DesignCapacity="26810"
      FullChargeCapacity="24780"
      CycleCount="14"
      ActiveAcTime="PT23H59M59S"
      ActiveDcTime="PT0S"
      CsAcTime="PT0S"
      CsDcTime="PT0S"
      ActiveDcEnergy="0"
      CsDcEnergy="0"
      EstimatedDesignActiveTime="PT0S"
      EstimatedFullChargeActiveTime="PT0S"
      EstimatedDesignCsTime="PT0S"
      EstimatedFullChargeCsTime="PT0S"
      BatteryChanged="0"
      />
    <HistoryEntry
      StartDate="2023-07-26T05:00:00Z"
      LocalStartDate="2023-07-26T00:00:00"
      EndDate="2023-07-27T04:59:59Z"
      LocalEndDate="2023-07-26T23:59:59"
      DesignCapacity="26810"
      FullChargeCapacity="24780"
      CycleCount="14"
      ActiveAcTime="PT23H59M59S"
      ActiveDcTime="PT0S"
      CsAcTime="PT0S"
      CsDcTime="PT0S"
      ActiveDcEnergy="0"
      CsDcEnergy="0"
      EstimatedDesignActiveTime="PT0S"
      EstimatedFullChargeActiveTime="PT0S"
      EstimatedDesignCsTime="PT0S"
      EstimatedFullChargeCsTime="PT0S"
      BatteryChanged="0"
      />
    <HistoryEntry
      StartDate="2023-07-27T05:00:00Z"
      LocalStartDate="2023-07-27T00:00:00"
      EndDate="2023-07-28T04:59:59Z"
      LocalEndDate="2023-07-27T23:59:59"
      DesignCapacity="26810"
      FullChargeCapacity="24780"
      CycleCount="14"
      ActiveAcTime="PT23H59M59S"
      ActiveDcTime="PT0S"
      CsAcTime="PT0S"
      CsDcTime="PT0S"
      ActiveDcEnergy="0"
      CsDcEnergy="0"
      EstimatedDesignActiveTime="PT0S"
      EstimatedFullChargeActiveTime="PT0S"
      EstimatedDesignCsTime="PT0S"
      EstimatedFullChargeCsTime="PT0S"
      BatteryChanged="0"
      />
  </History>
  <EnergyDrains>
  </EnergyDrains>
</BatteryReport>
